"""
Base module for RagKit, providing foundational classes and utilities for 
building and managing RAG (Retrieval-Augmented Generation) systems.
"""
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any


@dataclass
class Document:
    """
    Represents a document in the RAG system.
    Attributes:
        content (str): The textual content of the document.
        metadata (dict, optional): Additional metadata about the document.
        similarity_score (float, optional): A score indicating the similarity 
                                        of the document to a query or context.
    """
    content: str
    metadata: dict[str, Any] = field(default_factory=dict)
    similarity_score: float = 0.0    

@dataclass
class RAGResponse:
    """
    Represents a response generated by the RAG system.
    Attributes:
        answer (str): The generated answer or response.
        sources (list[Document]): A list of documents that were 
                                  used to generate the response.
    """
    answer: str
    sources: list[Document] = field(default_factory=list)

class BaseRAG(ABC):
    """
    Abstract base class for RAG systems.
    This class defines the interface for RAG systems, including methods for
    generating responses and ingesting documents.
    """
    @abstractmethod
    async def ingest(self,
                     documents: list[str | Document],
                     **kwargs: Any) -> None:
        """
        Ingests a list of documents into the RAG system.
        Args:
            documents (list[str | Document]): A list of Document instances or 
                                              raw text strings to be ingested.
        """

    @abstractmethod
    async def query(self, question: str, **kwargs: Any) -> RAGResponse:
        """
        Generates a response based on the provided question.
        Args:
            question (str): The input question for which a response is to be
                            generated.
        Returns:
            RAGResponse: The generated response along with the source documents.
        """

    @abstractmethod
    async def retrieve(self, question: str, **kwargs: Any) -> list[Document]:
        """
        Retrieves the most relevant documents for a question, without
        generating an answer -- for callers (e.g. an agent's own tool) that
        want ranked context to reason over themselves, rather than a
        second, redundant LLM-generated answer on top of their own.
        Args:
            question (str): The input question to retrieve context for.
        Returns:
            list[Document]: The retrieved Document instances, ranked most
                            relevant first.
        """